name: Defang
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: Whether to deploy up or down
        required: true
        default: up
        type: choice
        options:
          - up
          - down
      stack:
        description: The stack to deploy up or down. (Leave blank for default)
        default: ekai
jobs:
  defang:
    name: Defang ${{ github.event.inputs.action || 'up' }} ${{ github.event.inputs.stack || 'ekai' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    concurrency:
      cancel-in-progress: false
      group: deploy-defang-partner-${{ github.event.inputs.stack || 'ekai' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Defang ${{ github.event.inputs.action || 'up' }} ${{ github.event.inputs.stack || 'ekai' }}
        uses: DefangLabs/defang-github-action@v1.4.0
        with:
          command: ${{ github.event.inputs.action || 'up' }}
          project: defang-partner
          stack: ${{ github.event.inputs.stack || 'ekai' }}
      - name: Deployment Summary
        uses: DefangLabs/defang-github-action@v1.4.0
        with:
          command: services
          project: defang-partner
          stack: ${{ github.event.inputs.stack || 'ekai' }}
    environment: dev
